//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongShout.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid MessageId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public System.Guid SenderUserId { get; set; }
        public string SenderScreenName { get; set; }
        public string RecipientScreenName { get; set; }
        public string SongId { get; set; }
        public string SongName { get; set; }
        public string ArtistId { get; set; }
        public string ArtistName { get; set; }
        public string AlbumId { get; set; }
        public string AlbumName { get; set; }
        public string SongUrl { get; set; }
        public string SongShoutUrl { get; set; }
        public string FullMessage { get; set; }
        public string CustomMessage { get; set; }
        public System.DateTime Submitted { get; set; }
        public int ViewCount { get; set; }
    
        public virtual User User { get; set; }
    }
}
