//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongShout.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public System.Guid UserId { get; set; }
        public string emailAddress { get; set; }
        public string ScreenName { get; set; }
        public string Token { get; set; }
        public string TokenSecret { get; set; }
        public decimal TwitterUserId { get; set; }
        public string VerificationString { get; set; }
        public System.DateTime Submitted { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
    }
}
